AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectBucketName:
    Type: String
    Default: testing123-project-bucket

Resources:
  ProjectBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ProjectBucketName

Outputs:
  ProjectBucket:
    Value: !Ref ProjectBucket
