version: "3"

services:
  backend:
    restart: always
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
      - ~/.aws:/root/.aws
      - /var/run/docker.sock:/var/run/docker.sock
    command: sam local start-api --docker-volume-basedir "$PWD/backend" --host 0.0.0.0 --port 5000 --parameter-overrides ParameterKey=FrontendUrl,ParameterValue=http://localhost:3000

  frontend:
    restart: always
    build: ./frontend
    environment:
      - BROWSER=none
      - REACT_APP_BACKEND_URL=http://localhost:5000
    env_file:
      - local.env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - ~/.aws:/root/.aws
    depends_on:
      - backend
    entrypoint: sh /frontend/entrypoint.sh
