version: "3"

services:
  backend:
    restart: always
    build: ./backend
    environment:
      - basedir=$PWD/backend
      - frontend_url=http://localhost:3000
      - stack_name=$stack_name
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
      - ~/.aws:/root/.aws
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: sh /backend/entrypoint.sh

  frontend:
    restart: always
    build: ./frontend
    environment:
      - BROWSER=none
      - REACT_APP_BACKEND_URL=http://localhost:5000
      - stack_name=$stack_name
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - ~/.aws:/root/.aws
    depends_on:
      - backend
    entrypoint: sh /frontend/entrypoint.sh
